#ifndef EXIT_STATUS_H
#define EXIT_STATUS_H

typedef enum exit_status_e {
    SUCCESS = 0,
    END_OF_INPUT,
    UNKNOWN_ACTION,
    DIGIT_EXPECTED,
    INTEGER_TRAILING_CHARS,
    RATIONAL_DENUM_TRAILING_CHARS,
    DECFRAC_FRAC_TRAILING_CHARS
} exit_status;

#endif /* EXIT_STATUS_H */
